
<!-- Facebook Conversion Code for Checkouts -->
<script>(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', '<?php $this->_getPixelId() ?>', {'value':'<?php echo $this->_getValue() ?>','currency':'<?php echo $this->_getCurrency() ?>'}]);
</script>

<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=<?php $this->_getPixelId() ?>&amp;cd[value]=<?php echo $this->_getValue() ?>&amp;cd[currency]=<?php echo $this->_getCurrency() ?>&amp;noscript=1" /></noscript>
